### ISSUE TITLE
Made some updates including clip launcher 

### ISSUE THREAD

**Issue by Sebastian-blu** [kdejaeger/open-stage-control-bitwig#1]
Hey didn’t know how to contact ya directly but yeah I took what u made here and added some stuff. It’s on Kvr cheers. Thanks for helping me get started.

**Comment by kdejaeger** [comment]
I didn't get notified by GitHub. Just noticed your messages/issues. Anyway, what's the latest? I've not changed much as you probably figured out ... .

**Comment by vincenzoml** [comment]
@Sebastian-blu where is your clipboard launcher addition? Can you link it? Thanks!

**Comment by Sebastian-blu** [comment]
I have it for download on my GitHub page. I haven't been keeping up with what's going on here for a while now, but I am intending to get back to it sometime here. But what I have there is functional. I am not sure if it is my latest build or not.

**Comment by Sebastian-blu** [comment]
> I have it for download on my GitHub page. I haven't been keeping up with what's going on here for a while now, but I am intending to get back to it sometime here. But what I have there is functional. I am not sure if it is my latest build or not.



> @Sebastian-blu where is your clipboard launcher addition? Can you link it? Thanks!

see comment below.

**Comment by Sebastian-blu** [comment]
> @Sebastian-blu where is your clipboard launcher addition? Can you link it? Thanks!

see comment below :-)

**Comment by Sebastian-blu** [comment]
> @Sebastian-blu where is your clipboard launcher addition? Can you link it? Thanks!

hey :-) your message inspired me to put some more polish on project. So you can go to my GitHub page and download my open stage control implementation.

**Comment by vincenzoml** [comment]
@Sebastian-blu I thought I had left a reply here, but don't see it. I wanted to thank you for this! It's a cool thing you made. I reported two issues in your github.
