### ISSUE TITLE
here is the bitwig project I'm working on 

### ISSUE THREAD

**Issue by Sebastian-blu** [kdejaeger/open-stage-control-bitwig#2]
[barryCleanBitwigControlView copy.json.txt](https://github.com/kdejaeger/open-stage-control-bitwig/files/1835083/barryCleanBitwigControlView.copy.json.txt)
so I am using the trick of layering widgets a lot on this. You will see in the mixer page text over the top of vu meters. text with pointer actions turned off over faders. the clip launcher is a stack of rgb led under a button that has an opacity of 0. the led's match color of clips in bitwig. So it isn't as clean as what you are saying on the forum but it does work well. I would be interested how it works with drum pad stuff. let me know what you think 🤠

**Comment by kdejaeger** [comment]
Nicely done. I might use it if I ever get a large touchscreen.
