### ISSUE TITLE
Update to v1?

### ISSUE THREAD

**Issue by fractalf** [kdejaeger/open-stage-control-bitwig#4]
Any plans for updating this to work with Open Stage Control v1+ ?

ref: https://github.com/jean-emmanuel/open-stage-control/issues/751#issuecomment-922548179

**Comment by kdejaeger** [comment]
Hi, I'm not using Bitwig enough, so there's no drive for me to keep up to date with the latest version. The old version should work for a long time though, if there's no breaking changes in the mossgraber bitwig plugin.

**Comment by fractalf** [comment]
Thank you for your response. I get you, no problem. It probably works, but there's been quite a few changes in the v1, so the UI looks broken etc.

Anyway, it is what it is,
cheers :)
